services:
#  npm:
#    image: jc21/nginx-proxy-manager:latest
#    container_name: nginx-proxy-manager
#    ports:
#      - "80:80"
#      - "81:81"    # panel admina
#      - "443:443"
#    volumes:
#      - ./npm/data:/data
#      - ./npm/letsencrypt:/etc/letsencrypt
#    networks:
#      - przyczepki-network
#    restart: unless-stopped

  przyczepki_web:
    container_name: przyczepki_web
    build:
      context: .
      dockerfile: Dockerfile
#    image: wilczynski87/przyczepki-web
    environment:
      - TZ=Europe/Warsaw
      - APP_ENV=dev
    networks:
      - przyczepki-network
    restart: unless-stopped
    ports:
      - "80:80"

  przyczepki_api:
    build:
      context: .
      dockerfile: server/DockerfileServer
#    image: wilczynski87/przyczepki-api
    container_name: przyczepki_api
    environment:
      - TZ=Europe/Warsaw
      - DB_HOST=przyczepki_db
      - DB_PORT=27017
      - DB_NAME=przyczepki
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_AUTH_SOURCE=admin
      - API_ENV=dev
      - AUTH_SECRET_LOGIN=secretLogin
      - AUTH_SECRET_REFRESH=secretRefresh
      - AUTH_ISSUER=ktor
      - AUTH_AUDIENCE=ktor
      - AUTH_REALM=ktor
      - AUTH_ACCESS_TOKEN_EXPIRY=3600000
      - AUTH_REFRESH_TOKEN_EXPIRY=2592000000
      - AUTH_GOOGLE_CLIENT_ID=
      - AUTH_CLAIM=userId
      - EMAIL_HOST=localhost
      - EMAIL_PORT=8200
      - WEB_HOST=przyczepki_web
      - WEB_PORT=80
    networks:
      - przyczepki-network
    restart: unless-stopped
    depends_on:
      - przyczepki_db
    ports:
      - "8090:8090"

  przyczepki_db:
    image: mongo
    container_name: przyczepki_db
    restart: unless-stopped
    networks:
      - przyczepki-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"

networks:
  przyczepki-network:
    driver: bridge


